In [1]:
import numpy as np

Задание №1. Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [2]:
num = int(input('Задайте число N до 0: '))
x = np.flip(np.arange(0, num), 0)
x

Задайте число N до 0: 5


array([4, 3, 2, 1, 0])

Задание №2. Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [4]:
n = int(input('Задайте число N до 0:'))
x = np.diag(np.flip(np.arange(0, n), 0),0)
print(x)
print(f'Сумма элементов диагонали: {np.trace(x)}')

Задайте число N до 0:10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма элементов диагонали: 45


Задание №3. 
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [7]:
from numpy import linalg as li

a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3])
x = li.solve(a, b)
print (x)

[ 0.46666667  3.84444444 -5.55555556]


In [9]:
np.allclose(np.dot(a, x), b) #Проверка решения

True